"""Every error the package raises to its callers, each with a stable `code`."""

from forge.domain.errors import (
    Conflict,
    Forbidden,
    FreshSignInRequired,
    InvalidName,
    Misconfigured,
    NotFound,
    NotReady,
    PortError,
    Rejected,
    ServiceError,
    SessionExpired,
    SharedWorkflowOwner,
    SignInDenied,
    SignInInvalid,
    SoleAdmin,
    Unauthenticated,
    Unavailable,
    UniconError,
)

__all__ = [
    "Conflict",
    "Forbidden",
    "FreshSignInRequired",
    "InvalidName",
    "Misconfigured",
    "NotFound",
    "NotReady",
    "PortError",
    "Rejected",
    "ServiceError",
    "SessionExpired",
    "SharedWorkflowOwner",
    "SignInDenied",
    "SignInInvalid",
    "SoleAdmin",
    "Unauthenticated",
    "Unavailable",
    "UniconError",
]
