"""Every error the package raises to its callers, each with a stable `code`."""

from forge.domain.errors import (
    AdminOnly,
    ConfirmationRequired,
    Conflict,
    ContestantConflict,
    Forbidden,
    FreshSignInRequired,
    InvalidName,
    InvalidPath,
    Misconfigured,
    NotFound,
    NotReady,
    PortError,
    Rejected,
    ReservedPath,
    ServiceError,
    SessionExpired,
    SharedWorkflowOwner,
    SignInDenied,
    SignInInvalid,
    SoleAdmin,
    Unauthenticated,
    Unavailable,
    UniconError,
)
from forge.domain.yaml_models import InvalidDefinition

__all__ = [
    "AdminOnly",
    "ConfirmationRequired",
    "Conflict",
    "ContestantConflict",
    "Forbidden",
    "FreshSignInRequired",
    "InvalidDefinition",
    "InvalidName",
    "InvalidPath",
    "Misconfigured",
    "NotFound",
    "NotReady",
    "PortError",
    "Rejected",
    "ReservedPath",
    "ServiceError",
    "SessionExpired",
    "SharedWorkflowOwner",
    "SignInDenied",
    "SignInInvalid",
    "SoleAdmin",
    "Unauthenticated",
    "Unavailable",
    "UniconError",
]
